name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello project - Build Test
      id: hello-project-build-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hello project - Build Test
        setup-command: ''
        command: gcc hello.c  –o  hello.exe
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-PROJECT-BUILD-TEST_RESULTS: "${{steps.hello-project-build-test.outputs.result}}"
      with:
        runners: hello-project-build-test
