name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello Build Test
      id: hello-build-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hello Build Test
        setup-command: ''
        command: gcc hello.c -o hello_auto_grading.exe
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-BUILD-TEST_RESULTS: "${{steps.hello-build-test.outputs.result}}"
      with:
        runners: hello-build-test
